version: '3.8'
services:
    apollo-express:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4000:4000
        environment:
            - PG_HOST=apollo-express-server-postgres-1
            - PG_PORT=5432
            - PG_DB=postgres
            - PG_USER=postgres
            - PG_PASSWORD=SuperSecret!
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=SuperSecret!
        volumes:
            - ./pg_data:/var/lib/postgresql/data
            - ./sql:/docker-entrypoint-initdb.d
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 80:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=MyPass2022!
